version: '3.1'

services:
  mariaDB:
    image: mariadb
    
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ThothDB

    volumes:
      - ThothVault:/var/lib/mysql

    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8000:8080

volumes:
  ThothVault:

