version: '3.1'

services:
  mariaDB:
    image: mariadb
    
    secrets:
      - db-root-password
    
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-root-password
      - MYSQL_DATABASE=ThothDB

    volumes:
      - ThothVault:/var/lib/mysql

    ports:
      - 3306:3306
    networks:
      - ThothNet

  adminer:
    image: adminer
    ports:
      - 8000:8080
    networks:
      - ThothNet
volumes:
  ThothVault:

networks:
  ThothNet:
    driver: bridge

secrets:
  db-root-password:
    file: db/password.txt
