version: '3.1'

services:
  mariaDB:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ThothDB
    volumes:
      - ThothVault:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8009:8080

  backend:
    build: ./backend
    tty: true
    volumes:
      - ./backend:/thoth
    ports:
      - 8000:8000
    depends_on:
      - mariaDB

volumes:
  ThothVault:

