version: "3.1"

services:
  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ThothDB
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306