# Generated by Django 5.0.1 on 2024-01-28 02:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ope8id', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='ope8id_no_match', message='Has to be 8 digits', regex='\\w{8}$')], verbose_name='OPE8')),
                ('ope6id', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='ope6id_no_match', message='Has to be 6 digits', regex='\\w{6}$')], verbose_name='OPE6')),
                ('name', models.CharField(max_length=200, verbose_name='Organization Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=80, verbose_name='City')),
                ('state', models.CharField(choices=[('AL', 'ALABAMA'), ('AK', 'ALASKA'), ('AS', 'AMERICAN SAMOA'), ('AZ', 'ARIZONA'), ('AR', 'ARKANSAS'), ('CA', 'CALIFORNIA'), ('CO', 'COLORADO'), ('CT', 'CONNECTICUT'), ('DE', 'DELAWARE'), ('DC', 'DISTRICT OF COLUMBIA'), ('FL', 'FLORIDA'), ('GA', 'GEORGIA'), ('GU', 'GUAM'), ('HI', 'HAWAII'), ('ID', 'IDAHO'), ('IL', 'ILLINOIS'), ('IN', 'INDIANA'), ('IA', 'IOWA'), ('KS', 'KANSAS'), ('KY', 'KENTUCKY'), ('LA', 'LOUISIANA'), ('ME', 'MAINE'), ('MD', 'MARYLAND'), ('MA', 'MASSACHUSETTS'), ('MI', 'MICHIGAN'), ('MN', 'MINNESOTA'), ('MS', 'MISSISSIPPI'), ('MO', 'MISSOURI'), ('MT', 'MONTANA'), ('NE', 'NEBRASKA'), ('NV', 'NEVADA'), ('NH', 'NEW HAMPSHIRE'), ('NJ', 'NEW JERSEY'), ('NM', 'NEW MEXICO'), ('NY', 'NEW YORK'), ('NC', 'NORTH CAROLINA'), ('ND', 'NORTH DAKOTA'), ('MP', 'NORTHERN MARIANA IS'), ('OH', 'OHIO'), ('OK', 'OKLAHOMA'), ('OR', 'OREGON'), ('PA', 'PENNSYLVANIA'), ('PR', 'PUERTO RICO'), ('RI', 'RHODE ISLAND'), ('SC', 'SOUTH CAROLINA'), ('SD', 'SOUTH DAKOTA'), ('TN', 'TENNESSEE'), ('TX', 'TEXAS'), ('UT', 'UTAH'), ('VT', 'VERMONT'), ('VA', 'VIRGINIA'), ('VI', 'VIRGIN ISLANDS'), ('WA', 'WASHINGTON'), ('WV', 'WEST VIRGINIA'), ('WI', 'WISCONSIN'), ('WY', 'WYOMING')], max_length=2)),
                ('postal_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='postalcode_no_match', message='Invalid postal code', regex='^\\d{5}(?:[-\\s]\\d{4})?$')])),
                ('url', models.URLField(verbose_name='Homepage URL')),
                ('admission_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('average_sat', models.FloatField()),
                ('test_score', models.FloatField()),
                ('number_of_nra', models.PositiveIntegerField()),
                ('avg_cost_attendance', models.FloatField()),
                ('out_of_state_tuition', models.FloatField()),
                ('books_and_supplies', models.FloatField()),
                ('on_campus_exp', models.FloatField()),
                ('off_campus_exp', models.FloatField()),
                ('with_fam_exp', models.FloatField()),
                ('ratio_undergrad_faculty', models.DecimalField(decimal_places=2, max_digits=3)),
                ('lowest_temp', models.FloatField()),
                ('highest_temp', models.FloatField()),
                ('num_users_enrolled', models.PositiveIntegerField()),
                ('num_users_transferred', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ope6id', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='ope6id_no_match', message='Has to be 6 digits', regex='\\w{6}$')], verbose_name='OPE6')),
                ('cip', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateTimeField(auto_now_add=True)),
                ('grad_date', models.DateTimeField(auto_now_add=True)),
                ('nationality', models.CharField(max_length=12)),
                ('race', models.CharField(max_length=10)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
